caches:
  eyecache:
    displayName: Creepy Eye Cache
    description: Contains valuable items such as diamonds, powerful tools, and rarely custom items.
    items:
      -
        item: cobble
        weight: 3
        min: 1
        max: 1