caches:
  eyecache:
    displayName: Creepy Eye Cache
    description: Contains valuable items such as diamonds, powerful tools, and rarely
      custom items.
    items:
    - min: 1
      max: 1
      weight: 3
      type: RANDOMHEAD
    - item:
        ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_BLOCK
      min: 7
      max: 20
      weight: 10
      type: BASIC
    - item:
        ==: org.bukkit.inventory.ItemStack
        type: DIAMOND
      min: 25
      max: 64
      weight: 50
      type: BASIC
    - item: guns:blunderbuss
      min: 1
      max: 1
      weight: 1
      type: CUSTOM
    - item:
        ==: org.bukkit.inventory.ItemStack
        type: ELYTRA
      min: 1
      max: 1
      weight: 10
      type: BASIC
    - item:
        ==: org.bukkit.inventory.ItemStack
        type: PAPER
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: §rPet Certificate (§cFlame Fairy)
          lore:
          - §9Toys
          - §rGives the owner the right to
          - §rsummon a §cFlame Fairy
          - ''
          - §aUSAGE§r Right click to
          - §rpermanently bind this pet to
          - §ryou. Summon it with a Pet
          - §rLeash.
          internal: H4sIAAAAAAAAAONiYOBgEArPzCvJyEwt0nMuLS7Jz9XzdGHgL8mvLLYqSC0p1kvLScxNZQAAtkECzyoAAAA=
      min: 1
      max: 1
      weight: 10
      type: BASIC
